SELECT T1.FOOD_TYPE, T1.REST_ID, T1.REST_NAME, T1.FAVORITES
FROM REST_INFO AS T1
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS T2_MAX
     FROM REST_INFO
     GROUP BY FOOD_TYPE) AS T2
ON T1.FOOD_TYPE = T2.FOOD_TYPE AND T1.FAVORITES = T2.T2_MAX
ORDER BY FOOD_TYPE DESC