SELECT APNT_NO
    , PT_NAME
    , PATIENT.PT_NO
    , APPOINTMENT.MCDP_CD
    , (select DR_NAME from DOCTOR where DR_ID = MDDR_ID) as DR_NAME 
    , APNT_YMD
FROM APPOINTMENT
INNER JOIN PATIENT 
    ON APPOINTMENT.PT_NO = PATIENT.PT_NO
WHERE 1=1
AND LEFT(APNT_YMD,10) = '2022-04-13'
AND APNT_CNCL_YN = 'N'
AND APPOINTMENT.MCDP_CD = 'CS'
ORDER BY APNT_YMD